name: C/C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
      
jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc-12 g++-12 libopencv-dev

      - name: Install NVIDIA/CUDA
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt-get update
          sudo apt-get -y install cuda
          
      - name: Build Unit Test
        run: |
          chmod +x run.sh
          ./run.sh
          cd ./test
          make
          
      - name: Run tests
        run: |
          cd test
          echo $(test 1) >> $GITHUB_OUTPUT
#          echo $(test 2) >> $GITHUB_OUTPUT
          test
        id: run_tests
        env:
            MIX_ENV: test
            PGHOST: localhost
            PGUSER: postgres

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: ${{join(steps.run_tests.outputs.*, '\n')}}
          SLACK_TITLE: CI Test Suite
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}


