name: C/C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
      
jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Uncomment and modify this step to set up CUDA if needed
      # - name: Set up CUDA
      #   uses: nvidia/cuda@vX.Y
      #   with:
      #     cuda-version: 12.2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc-12 g++-12 libopencv-dev

      - name: Install NVIDIA/CUDA
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt-get update
          sudo apt-get -y install cuda
          
      - name: Build Unit Test
        run: |
          chmod +x run.sh
          ./run.sh
          cd ./test
          make
          
      - name: Run tests
        run: |
          cd test
          test

